Mount EFS file into ECS container instances

diff --git a/src/aws/cloudformation/templates/ecs-cluster-stack.yml b/src/aws/cloudformation/templates/ecs-cluster-stack.yml
--- a/src/aws/cloudformation/templates/ecs-cluster-stack.yml
+++ b/src/aws/cloudformation/templates/ecs-cluster-stack.yml
@@ -172,8 +172,64 @@ Resources:
         Fn::Base64: !Sub |
           #!/bin/bash
           yum update -y
+
           # Specify which cluster to join
           echo ECS_CLUSTER=${EcsClusterName} >> /etc/ecs/ecs.config
+
+          # Install jq, a JSON parser
+          yum -y install jq
+
+          # Install NFS client
+          if ! rpm -qa | grep -qw nfs-utils; then
+            yum -y install nfs-utils
+          fi
+
+          # Install Python 2.7, pip, and the AWS CLI
+          if ! rpm -qa | grep -qw python27; then
+            yum -y install python27
+          fi
+          yum -y install python27-pip
+          pip install awscli
+
+          # Add EFS support to the CLI configuration
+          aws configure set preview.efs true
+
+          # Get the instance's region from instance metadata
+          EC2_AVAIL_ZONE=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
+          EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
+
+          # Create a mount point for the EFS file system
+          mkdir /mnt/efs
+
+          # Get the EFS FileSystemID attribute
+          # (Note: The instance must have an EC2 role that gives the instance at
+          # least read access to EFS)
+          EFS_FILE_SYSTEM_ID=$(
+            /usr/local/bin/aws efs describe-file-systems \
+              --region $EC2_REGION \
+              | jq '.FileSystems[]' \
+              | jq 'select(.Name=="efs-docker")' | jq -r '.FileSystemId' \
+          )
+          # Check to see if the variable is set. If not, then exit.
+          if [-z "$EFS_FILE_SYSTEM_ID"]; then
+            echo "ERROR: variable not set" 1> /etc/efssetup.log
+            exit
+          fi
+
+          # Instance needs to belong to a security group that allows 2049 inbound/outbound
+          # The security group that the instance belongs to has to be added to EFS file system configuration
+          # Create variables for source and target
+          DIR_SRC=$EC2_AVAIL_ZONE.$EFS_FILE_SYSTEM_ID.efs.$EC2_REGION.amazonaws.com
+          DIR_TGT=/mnt/efs
+
+          # Mount EFS file system
+          mount -t nfs4 $DIR_SRC:/ $DIR_TGT
+
+          # Backup fstab
+          cp -p /etc/fstab /etc/fstab.back-$(date +%F)
+
+          # Append line to fstab
+          echo -e "$DIR_SRC:/ \t\t $DIR_TGT \t\t nfs \t\t defaults \t\t 0 \t\t 0" | tee -a /etc/fstab
 
   TargetGroup:
     Type: AWS::ElasticLoadBalancingV2::TargetGroup
